apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
  namespace: default
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: brendanburns/journal-server:latest
          imagePullPolicy: IfNotPresent
          env:
          - name: JOURNAL_ENTRIES
            valueFrom:
              configMapKeyRef:
                name: frontend-config
                key: journalEntries
          volumeMounts:
          - name: passwd-volume
            readOnly: true
            mountPath: "/etc/redis-passwd"
          resources:
            requests:
              cpu: "1.0"
              memory: "1G"
            limits:
              cpu: "1.0"
              memory: "1G"
      volumes:
      - name: passwd-volume
        secret: 
          secretName: redis-passwd
#     volumes:
#     - name: passwd-volume
#        emptyDir: {}
