apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
  namespace: default
spec:
  replicas: 2
  selector: 
    matchLables:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          images: my-repo/journal-server:v1-abcde
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: passwd-volume
            readOnly: true
            mountPath: "/etc/redis-paswd"
          resource:
            requests:
              cpu: "1.0"
              memory: "1G"
            limits:
              cpu: "1.0"
              memory: "1G"
      volume:
      - name: passwd-volume
        secret: 
          secretName: redis-passwd


